"""empty message

Revision ID: 94424799bcde
Revises: c91ab2be9e00
Create Date: 2025-08-29 02:02:27.722755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94424799bcde'
down_revision = 'c91ab2be9e00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
